version: '3.8'

services:
  yt-nfo-generator:
    build: .
    container_name: youtubedatafetch
    volumes:
      - ${MEDIA_HOST_PATH}:/media

    environment:
      MONGODB_URI: ${MONGODB_URI}
      MEDIA_ROOT: "/media"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: "no"





