
services:
  yt-nfo-generator:
    build: .
    container_name: youtubedatafetch

    volumes:
      - ${MEDIA_HOST_PATH}:/media

    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: tubearchivist
      SOURCE_COLLECTION: jellyfin_sync
      MEDIA_ROOT: /media
      REGENERATE_NFO: ${REGENERATE_NFO}

      REQUIRE_THUMBNAIL: "false"

      YTDLP_LIMIT_RATE: 2M
      YTDLP_CONCURRENT_FRAGMENTS: "1"
      YTDLP_RETRIES: "3"
      YTDLP_RETRY_SLEEP: "2"

    dns:
      - 1.1.1.1
      - 1.0.0.1

    restart: "no"
